apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: budgetanalyzer-local-wildcard-tls
  namespace: default
spec:
  isCA: false
  privateKey:
    rotationPolicy: Always
  secretName: budgetanalyzer-local-wildcard-tls
  dnsNames:
  - "*.budgetanalyzer.local"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
